version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3421:3000" # Expose application on port 3000
    environment:
      # Set environment variables for the application
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
      REDIS_URL: "redis://redis:6379"
      WERELEAF_NODE_ENV: "production"
      WERELEAF_PORT: 3421
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis on port 6379

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage

volumes:
  postgres_data:
